# Generated by Django 2.0.2 on 2018-03-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fans_1_Item_dj',
            fields=[
                ('master_id', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('follow_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('statuses_count', models.IntegerField()),
                ('verified_type', models.IntegerField()),
                ('sceen_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fans_2_Item_dj',
            fields=[
                ('master_id', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('follow_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('verified_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='post_Item_dj',
            fields=[
                ('author_id', models.IntegerField()),
                ('attitudes_count', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('created_at', models.CharField(max_length=20)),
                ('created_at_org', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pics', models.BooleanField()),
                ('reposts_count', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('retweeted_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserItem_dj',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('follow_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('statuses_count', models.IntegerField()),
                ('verified_type', models.IntegerField()),
                ('sceen_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
