# Generated by Django 2.0.2 on 2018-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fans_1_Item_dj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=100)),
                ('follow_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('statuses_count', models.IntegerField()),
                ('verified_type', models.IntegerField()),
                ('screen_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150, null=True)),
                ('mbrank', models.IntegerField()),
                ('mbtype', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fans_2_Item_dj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=100)),
                ('follow_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('verified_type', models.IntegerField()),
                ('mbrank', models.IntegerField()),
                ('mbtype', models.IntegerField()),
                ('screen_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post_Item_dj',
            fields=[
                ('author_id', models.CharField(max_length=100)),
                ('attitudes_count', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('created_at', models.CharField(max_length=20)),
                ('created_at_org', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pics', models.BooleanField()),
                ('reposts_count', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('retweeted_status', models.BooleanField()),
                ('retweeted_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem_dj',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('follow_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('statuses_count', models.IntegerField()),
                ('verified_type', models.IntegerField()),
                ('screen_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('avatar_hd', models.TextField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fans_2_item_dj',
            unique_together={('sid', 'master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='fans_1_item_dj',
            unique_together={('sid', 'master_id')},
        ),
    ]
