# Generated by Django 2.0.2 on 2018-03-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fans_1_item_dj',
            old_name='sceen_name',
            new_name='screen_name',
        ),
        migrations.RenameField(
            model_name='useritem_dj',
            old_name='sceen_name',
            new_name='screen_name',
        ),
    ]
