# Generated by Django 2.0.2 on 2018-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0002_post_item_dj_is_crawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_item_dj',
            name='author_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_item_dj',
            name='created_at_org',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post_item_dj',
            name='pics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post_item_dj',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
