# Generated by Django 2.0.2 on 2018-04-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0004_auto_20180412_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_item_dj',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
