# Generated by Django 2.0.2 on 2018-03-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0004_auto_20180307_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_item_dj',
            name='retweeted_text',
            field=models.TextField(null=True),
        ),
    ]
