# Generated by Django 2.0.2 on 2018-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0005_comments_item_dj_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_item_dj',
            name='score',
            field=models.FloatField(default=-1),
        ),
    ]
