# Generated by Django 2.0.2 on 2018-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0005_post_item_dj_retweeted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem_dj',
            name='avatar_hd',
            field=models.TextField(null=True),
        ),
    ]
