# Generated by Django 2.0.2 on 2018-03-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0006_useritem_dj_avatar_hd'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('master_id', models.IntegerField()),
                ('test_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='test_model',
            unique_together={('id', 'master_id')},
        ),
    ]
