# Generated by Django 2.0.2 on 2018-03-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0007_auto_20180311_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_model',
        ),
    ]
