# Generated by Django 2.0.2 on 2018-03-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0008_delete_test_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('master_id', models.IntegerField()),
                ('test_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='test_model',
            unique_together={('sid', 'master_id')},
        ),
    ]
