# Generated by Django 2.0.2 on 2018-03-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0009_auto_20180311_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_model',
        ),
        migrations.AddField(
            model_name='fans_1_item_dj',
            name='sid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fans_2_item_dj',
            name='sid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fans_1_item_dj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fans_2_item_dj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post_item_dj',
            name='author_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post_item_dj',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scrapyitem',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='fans_1_item_dj',
            unique_together={('sid', 'master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='fans_2_item_dj',
            unique_together={('sid', 'master_id')},
        ),
    ]
