# Generated by Django 2.0.2 on 2018-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_model',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
